[package]
name = "indexer-store"
version.workspace = true
edition.workspace = true

[dependencies]
indexer-core.workspace = true
alloy-primitives.workspace = true
dashmap.workspace = true
parking_lot.workspace = true
tokio.workspace = true
tracing.workspace = true
